---

- name: Provision vm
  hosts: all
  tasks:

    - name: Update apt package manager
      apt:
        update_cache: yes
      become: yes
    
    - name: Install docker
      apt:
        name: docker.io
        state: present
      become: yes
    
    - name: Docker user group
      command: usermod -aG docker vagrant
      become: yes